# Values formatted like "_env:ENV_VAR_NAME:default_value" can be overridden by the specified environment variable.
# See https://github.com/yesodweb/yesod/wiki/Configuration#overriding-configuration-values-with-environment-variables

static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:*4" # any IPv4 host
port:           "_env:PORT:3000"
approot:        "_env:APPROOT:http://localhost:3000"
ip-from-header: "_env:IP_FROM_HEADER:false"

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# development: false
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false

database:
  database: "_env:SQLITE_DATABASE:leport-web.sqlite3"
  poolsize: "_env:SQLITE_POOLSIZE:10"

copyright: Hiromi ISHII (c) 2015

package-dbs: []
trusted-packages:
  ["base", "containers", "QuickCheck","fgl","array"
  ,"async","binary","attoparsec","case-insensitive"
  ,"deepseq","hashable","haskeline"
  ,"hoopl","html","mtl","integer-gmp"
  ,"old-locale","old-time","time","parallel","parsec"
  ,"pretty","primitive","random","regex-base","regex-compat"
  ,"regex-posix","rts","split","stm","syb","template-haskell"
  ,"text","transformers","unordered-containers","vector","xhtml"]

distrusted-packages:
  ["process", "HTTP", "Cabal", "HUnit"
  ,"directory", "filepath", "ghc", "hint","ghc-prim"
  ,"network","terminfo","unix","zlib"]

distributed-port: 44444

#analytics: UA-YOURCODE
