Default: &defaults
  database: leport-web.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: leport-web_test.sqlite3
  <<: *defaults

Staging:
  database: leport-web_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: leport-web_production.sqlite3
  poolsize: 100
  <<: *defaults
